### ISSUE TITLE
Sending Frames from Unity to Python

### ISSUE THREAD

**Issue by Terminou** [off99555/Unity3D-Python-Communication#10] opened 2020-06-04 00:49 UTC
Hello, 

I have an object classification model on Python which is trained using Keras. I want to get frames from Unity and analyze the frames on Python. Is it possible? If it is, can you explain?

**Comment by offchan42** [comment] 2020-06-04 07:41
This is not related to the project. You need to find out how to read images in Unity and convert it into a bytes array so that it can be sent via ZeroMQ. Anything that can be converted to bytes can be transferred via ZeroMQ. Then in python, you need to decode the bytes array into an image.

 If the image comes from the Unity scene then you must do what I described above.
But I would suggest you read the image in python in the first place if it's an image that comes from the camera so that you don't have to be transferring the image via ZeroMQ.

**Closed as completed** 2020-06-04 07:53 UTC

**Comment by Terminou** [comment] 2020-06-06 18:49
As you can see in the screenshots from I produce byte array and save it as PNG. This shows that I have a bytes array of the corresponding frame. Now as you can see I need to send this array to Python and decode the bytes array into an image.

![image](https://user-images.githubusercontent.com/27548058/83952013-7e61d180-a83e-11ea-9059-3d0db8fd1699.png)

![image](https://user-images.githubusercontent.com/27548058/83952043-a94c2580-a83e-11ea-9b95-0c031576c3bf.png)

I changed the labeled part from your code but it did not work. Can you please help me with that? Thank you in advance.

![image](https://user-images.githubusercontent.com/27548058/83952161-8110f680-a83f-11ea-8fce-b56893bc98c4.png)

**Comment by offchan42** [comment] 2020-06-07 08:00
To solve this problem, it's mainly about your debugging skills. Instead of sending the image array, try to create a simple static byte array and send it. It will make you know whether your image array is the problem or the SendFrame function is the problem. Narrowing down problems like this will make you identify the bug quicker. Because now for you the problem is very vague as you only know that "it does not work", you don't even know what exactly does not work.

**Comment by Terminou** [comment] 2020-06-07 20:08
I tried everything to stream Unity's camera frames to Python but could not figure out. Can you add this functionality to your repository? I'd be glad if you help me on that subject.

Thank you!

**Comment by offchan42** [comment] 2020-06-07 21:20
Did you try what I suggested about sending a static byte array yet? If you haven't or don't understand, you probably need a programming course or book. You need to hone your debugging skills.
This repository is supposed to be minimal so that it's approachable by anyone. I don't want to put an unnecessary learning curve for people. And even if I help you on this subject, you will later have a harder problem that you cannot solve, because the root of your problem is debugging skills.

**Comment by Terminou** [comment] 2020-06-09 20:53
I handled the problem. Now I am able to send images from Unity to Python. Thanks 👍
